### ISSUE TITLE
Not sending via Delayed Job

### ISSUE THREAD

**Issue by humansounds** [sendwithus/sendwithus_ruby_action_mailer#24]
I see the notes for sending with sidekiq, but will this work with DJ?  It doesn't seem to off the shelf, as DJ requires you to remove the `.deliver` method at the end of the mailer call.  Advice?

**Comment by humansounds** [comment]
See: https://github.com/collectiveidea/delayed_job/#rails-3-mailers

**Comment by bmulholland** [comment]
@humansounds I'm not very familiar with DJ, but I just had a poke around their source. Seems like they do something very similar to Sidekiq, so you should be able to do a slight modification of the Sidekiq instructions:
`::SendWithUsMailer::Base.extend(Delayed::DelayMail)`

Can you try that in your SWU initializer and let me know if that works?

**Comment by humansounds** [comment]
Perfect!  That did it :+1: 

Thanks for the quick response.
