### ISSUE TITLE
Route helpers

### ISSUE THREAD

**Issue by vdmgolub** [sendwithus/sendwithus_ruby_action_mailer#30]
Hi, could you suggest how I can use route helpers in a mailer?

**Comment by vdmgolub** [comment]
Well, found a working solution, still looks hacky to me :(
```ruby
class BaseMailer < SendWithUsMailer::Base
  include Rails.application.routes.url_helpers

  def initialize(method_name, *args)
    self.default_url_options = Rails.configuration.action_mailer.default_url_options
    super
  end
end
```

**Comment by demoore** [comment]
Hey @vdmgolub your hacky solution seemed cool. Did that end up not working?

**Comment by vdmgolub** [comment]
Yep, it didn't work (was playing in pry with it and it seemed okay, but the actual code didn't pick up routes anyway) :( I ended up with custom implementation without your gem.

**Comment by momolog** [comment]
So how **do** we use route helpers in mailers derived from `SendWithUsMailer::Base` ?
