### ISSUE TITLE
Is it possible to cancel the email sending?

### ISSUE THREAD

**Issue by Ricardonacif** [sendwithus/sendwithus_ruby_action_mailer#31]
Hey guys,

is it possible to cancel sending the email on the body of the method due to a conditional?

**Comment by demoore** [comment]
Hey @Ricardonacif there isn't a way to cancel to a send. What are you trying to do? If possible, it might be better to use the [sendwithus ruby gem](https://github.com/sendwithus/sendwithus_ruby).

**Comment by Ricardonacif** [comment]
@demoore I'd like to do something like:


```ruby
class SendEmail < SendWithUsMailer::Base
  include ActionView::Helpers::TextHelper

  def send_email(user_id)
    user = User.find user_id
    
    if user.should_receive_email?
      assign(:user, user)
      mail(
        email_id: "XXXXXXXX",
        recipient_address: user.email
      )
    end
  end

end
```

but I get an error:

```
SendWithUs::ApiNilEmailId: email_id cannot be nil
```

**Comment by demoore** [comment]
Gotcha, there's not a way to do that. One thing you could do is rely on your unsubscribe list to stop emails from going out. ESPs will block sends to users that have unsubscribed.

**Comment by Ricardonacif** [comment]
Got it. The should_receive_email was just an example, actually I wanna cancel delivery depending on other stuff not related to the user. Can I create a PR for that?

**Comment by demoore** [comment]
Yeah of course! We love PRs. :smile:
