### ISSUE TITLE
Does this work with ActionMailer's interceptors and observers?

### ISSUE THREAD

**Issue by plainlystated** [sendwithus/sendwithus_ruby_action_mailer#36]

**Comment by demoore** [comment]
This gem is only an ActionMailer-like wrapper around [Sendwithus' Ruby client](https://github.com/sendwithus/sendwithus_ruby), so using AcitonMailer's interceptors and observers wouldn't work.

**Comment by momolog** [comment]
@demoore Are there any plans to provide an ActionMailer compatible implementation?

**Comment by demoore** [comment]
@momolog not currently. We like pull requests, though! So if have any ideas I'd be happy to take a look.
